services:
  frontend:
    image: ghcr.io/entryfra/preview-deployment-frontend:latest

    labels:
      - traefik.enable=true
      - traefik.http.routers.production.rule=Host(`santailya.ru`)
      - traefik.http.routers.production.entrypoints=web
      - traefik.http.services.production.loadbalancer.server.port=80

    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
    name: preview-deployment-lab_default
