services:
  frontend-preview:
    # Берём готовый образ из GHCR.
    # PR_NUMBER превратится, например, в pr-2.
    image: ghcr.io/entryfra/preview-deployment-frontend:pr-${PR_NUMBER}

    labels:
      - traefik.enable=true

      # Для PR №2 получится адрес pr-2.localhost
      - traefik.http.routers.frontend-pr-${PR_NUMBER}.rule=Host(`pr-${PR_NUMBER}.preview.santailya.ru`)
      - traefik.http.routers.frontend-pr-${PR_NUMBER}.entrypoints=web

      # Frontend внутри контейнера слушает порт 80
      - traefik.http.services.frontend-pr-${PR_NUMBER}.loadbalancer.server.port=80

    # Подключаем preview к сети, где находится общий Traefik
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
    name: preview-deployment-lab_default
