services:
  
  traefik:
    image: traefik:v3.6
    container_name: traefik

    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80

    ports:
      - "8080:8080"
      - "80:80"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.server.port=80  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=3000

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: petdb
      DB_USER: petuser
      DB_PASSWORD: petpassword

    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_DB: petdb
      POSTGRES_USER: petuser
      POSTGRES_PASSWORD: petpassword

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
