name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Собрать Docker-образы
        run: docker compose build
